"""
report_generator.py
───────────────────
AI-powered forensic narrative report generator.

Produces a structured, nuanced forensic intent report from scan results —
going beyond simple scoring to provide court-admissible, examiner-quality
analysis with specific technical observations, contextual interpretation,
and professional conclusions.

Report Sections:
    1. Executive Summary      — one-paragraph verdict for non-technical readers
    2. Technical Findings     — detailed block/region analysis
    3. Wipe Pattern Analysis  — per-type breakdown and tool attribution
    4. Temporal Context       — what the wipe patterns tell us about timing
    5. ML Confidence Summary  — how ML classification affected results
    6. Evidence Reliability   — honest assessment of confidence and caveats
    7. Examiner Conclusions   — final forensic opinion with caveats
    8. Recommended Actions    — next investigative steps

The report is NOT generated by an external AI API — it uses a structured
template engine that applies forensic logic from the scan results to
produce professional, evidence-specific language. This ensures:
    - Reproducibility (same results = same report)
    - No external API dependency
    - No hallucination risk on evidence-critical details
    - Court-admissible traceability

Usage:
    from engine.report_generator import generate_report

    report = generate_report(
        session_id   = "SID-A3F8C21E",
        filename     = "suspect.dd",
        sha256       = "e3b0c44...",
        size_bytes   = 4294967296,
        stats        = scan_stats,
        regions      = regions,
        blocks       = block_results,
        custody      = custody_chain,
        ml_summary   = ml_summary_dict,
    )
    # report is a dict with all sections
    # Embed in analysis JSON as report["narrative"]
"""

import math
from datetime import datetime, timezone
from typing import List, Optional


# ─────────────────────────────────────────────────────────────────────────────
# TOOL ATTRIBUTION DATABASE
# ─────────────────────────────────────────────────────────────────────────────

_TOOL_SIGNATURES = {
    "ZERO_WIPE": {
        "tools":     ["dd (if=/dev/zero)", "sdelete -z", "cipher /w:", "Windows format /P:1"],
        "standard":  "NIST SP 800-88 — single-pass zero overwrite",
        "context":   "Single-pass zero-fill is the fastest and most common wipe method. "
                     "It is effective against software recovery but may not defeat "
                     "advanced forensic hardware imaging.",
    },
    "FF_WIPE": {
        "tools":     ["dd (if=/dev/urandom truncated)", "hdparm --security-erase", "Flash erase"],
        "standard":  "Common in embedded/flash memory secure erase",
        "context":   "0xFF fill is the erase state of NAND flash memory and some firmware "
                     "regions. On a hard disk, sustained 0xFF fills indicate deliberate wiping "
                     "rather than unwritten space.",
    },
    "RANDOM_WIPE": {
        "tools":     ["shred", "dd (if=/dev/urandom)", "Eraser", "DBAN random pass",
                      "sdelete -p", "srm"],
        "standard":  "NIST SP 800-88 / DoD 5220.22-M compliant random overwrite",
        "context":   "Pseudorandom overwrite is considered the most secure software wipe "
                     "method. It produces cryptographically random output indistinguishable "
                     "from AES-encrypted data at the individual block level.",
    },
    "MULTI_PASS": {
        "tools":     ["shred -n 3/7", "DBAN Gutmann (35-pass)", "DoD 5220.22-M (7-pass)",
                      "Eraser Gutmann", "Blancco"],
        "standard":  "Gutmann method / DoD 5220.22-M — multi-pass overwrite",
        "context":   "Multi-pass overwrite with alternating patterns is consistent with "
                     "enterprise-grade secure erasure tools. The presence of alternating "
                     "band sequences (zero/FF/random) is a strong indicator of deliberate, "
                     "methodical anti-forensic activity.",
    },
    "LIKELY_ZERO_WIPE": {
        "tools":     ["Interrupted zero-fill", "Partial wipe", "TRIM-affected sectors"],
        "standard":  "Partial evidence — incomplete overwrite",
        "context":   "Partial zero-fill blocks indicate either an interrupted wipe process "
                     "or targeted overwriting of specific file regions.",
    },
    "LIKELY_FF_WIPE": {
        "tools":     ["Interrupted FF-fill", "Flash device residue"],
        "standard":  "Partial evidence — incomplete overwrite",
        "context":   "Partial 0xFF fill in a non-flash context is a weak but notable indicator.",
    },
}


# ─────────────────────────────────────────────────────────────────────────────
# REPORT GENERATION
# ─────────────────────────────────────────────────────────────────────────────

def generate_report(
    session_id:  str,
    filename:    str,
    sha256:      str,
    size_bytes:  int,
    stats,
    regions:     list,
    blocks:      list,
    custody=None,
    ml_summary:  Optional[dict] = None,
) -> dict:
    """
    Generate a complete forensic narrative report.

    Parameters
    ----------
    stats   : ScanStats object from scorer.py
    regions : list of Region objects from aggregator.py
    blocks  : list of BlockResult objects from classifier.py
    custody : CustodyChain object (optional)
    ml_summary : dict with ML classification summary stats

    Returns
    -------
    dict with all report sections, suitable for embedding in analysis JSON
    """
    now = datetime.now(timezone.utc).isoformat()

    # ── Compute derived statistics ────────────────────────────────────────────
    stats_d = stats.to_dict() if hasattr(stats, 'to_dict') else stats

    total     = stats_d["total_blocks"]
    susp      = stats_d["suspicious_blocks"]
    density   = stats_d["wipe_density"]
    score     = stats_d["intent_score"]
    verdict   = stats_d["verdict"]
    n_regions = stats_d["regions_count"]
    avg_ent   = stats_d["avg_entropy_flagged"]
    wipe_types = stats_d.get("wipe_type_counts", {})

    size_human = _fmt_bytes(size_bytes)
    total_blocks = total
    coverage_pct = round(density * 100, 2)

    # Dominant wipe type
    dominant_type = max(wipe_types, key=lambda k: wipe_types[k]) \
                    if wipe_types else "UNKNOWN"
    has_random    = wipe_types.get("RANDOM_WIPE", 0) > 0
    has_multi     = wipe_types.get("MULTI_PASS", 0) > 0
    has_zero      = wipe_types.get("ZERO_WIPE", 0) > 0
    has_ff        = wipe_types.get("FF_WIPE", 0) > 0

    # Region analysis
    region_dicts = [r.to_dict() if hasattr(r, 'to_dict') else r for r in regions]
    largest_region = max(region_dicts, key=lambda r: r.get("size", 0)) \
                     if region_dicts else None
    avg_region_size = (sum(r.get("size", 0) for r in region_dicts) / n_regions) \
                      if n_regions > 0 else 0

    # ── Section 1: Executive Summary ─────────────────────────────────────────
    executive_summary = _executive_summary(
        verdict, score, filename, size_human,
        coverage_pct, n_regions, has_random, has_multi,
        dominant_type, total_blocks, susp,
    )

    # ── Section 2: Technical Findings ────────────────────────────────────────
    technical_findings = _technical_findings(
        filename, sha256, size_bytes, size_human,
        total_blocks, susp, coverage_pct, n_regions,
        avg_ent, region_dicts, largest_region, avg_region_size,
    )

    # ── Section 3: Wipe Pattern Analysis ─────────────────────────────────────
    pattern_analysis = _pattern_analysis(
        wipe_types, region_dicts, has_random, has_multi,
        has_zero, has_ff,
    )

    # ── Section 4: Evidence Reliability ──────────────────────────────────────
    reliability = _reliability_assessment(
        score, verdict, density, n_regions,
        avg_ent, wipe_types, ml_summary,
    )

    # ── Section 5: ML Summary ────────────────────────────────────────────────
    ml_section = _ml_section(ml_summary)

    # ── Section 6: Conclusions ────────────────────────────────────────────────
    conclusions = _conclusions(
        verdict, score, filename, has_random, has_multi,
        n_regions, coverage_pct, density,
    )

    # ── Section 7: Recommended Actions ───────────────────────────────────────
    recommended_actions = _recommended_actions(
        verdict, has_random, has_multi, n_regions,
        score=score, has_zero=has_zero, has_ff=has_ff,
        coverage_pct=coverage_pct,
    )

    # ── Assemble final report ─────────────────────────────────────────────────
    report = {
        "generated_at": now,
        "session_id":   session_id,
        "report_version": "1.0",
        "examiner_note": (
            "This report was generated automatically by WipeTrace using "
            "rule-based and machine learning analysis of the provided disk image. "
            "It should be reviewed by a qualified digital forensics examiner before "
            "submission to any legal proceedings."
        ),
        "executive_summary": executive_summary,
        "technical_findings": technical_findings,
        "pattern_analysis":   pattern_analysis,
        "reliability":        reliability,
        "ml_analysis":        ml_section,
        "conclusions":        conclusions,
        "recommended_actions": recommended_actions,
        "metrics": {
            "intent_score":    score,
            "verdict":         verdict,
            "coverage_pct":    coverage_pct,
            "regions_found":   n_regions,
            "suspicious_pct":  round(susp / total * 100, 2) if total > 0 else 0,
            "dominant_type":   dominant_type,
            "has_multi_pass":  has_multi,
            "has_random_wipe": has_random,
        },
    }

    return report


# ─────────────────────────────────────────────────────────────────────────────
# SECTION BUILDERS
# ─────────────────────────────────────────────────────────────────────────────

def _executive_summary(verdict, score, filename, size_human, coverage_pct,
                        n_regions, has_random, has_multi, dominant_type,
                        total_blocks, susp) -> str:

    verdict_phrases = {
        "HIGH":       "strong evidence of deliberate anti-forensic activity",
        "MEDIUM":     "moderate evidence consistent with deliberate data elimination",
        "LOW":        "limited evidence of wipe activity that warrants further investigation",
        "NEGLIGIBLE": "no significant evidence of deliberate data wiping",
    }
    phrase = verdict_phrases.get(verdict, "inconclusive findings")

    para = (
        f"Forensic analysis of '{filename}' ({size_human}) has identified "
        f"{phrase}. "
        f"The WipeTrace intent scoring model assigned an intent score of "
        f"{score}/100 with a verdict of {verdict}. "
    )

    if verdict in ("HIGH", "MEDIUM"):
        para += (
            f"Wipe artefacts were detected across {coverage_pct:.1f}% of the disk "
            f"surface, distributed across {n_regions} distinct region{'s' if n_regions != 1 else ''}. "
        )
        if has_multi:
            para += (
                "The presence of alternating multi-pass wipe patterns is consistent with "
                "enterprise-grade secure erasure tools such as DBAN, shred, or Blancco. "
                "Multi-pass wiping is rarely performed inadvertently and represents "
                "a strong indicator of deliberate anti-forensic intent. "
            )
        elif has_random:
            para += (
                "Cryptographically random overwrite patterns were identified, consistent "
                "with tools such as shred, dd with /dev/urandom, or commercial erasure software. "
            )
        if susp > 0 and total_blocks > 0:
            para += (
                f"A total of {susp:,} blocks ({coverage_pct:.1f}%) exhibit wipe signatures. "
            )
    elif verdict == "LOW":
        para += (
            f"While {n_regions} wipe region{'s were' if n_regions != 1 else ' was'} detected, "
            f"the overall density and confidence are insufficient to assert deliberate wiping "
            f"without corroborating evidence. "
        )
    else:
        para += (
            "The disk image shows no statistically significant wipe patterns. "
            "Observed anomalies are consistent with normal filesystem operations, "
            "sparse file allocation, or unwritten sectors. "
        )

    return para.strip()


def _technical_findings(filename, sha256, size_bytes, size_human,
                         total_blocks, susp, coverage_pct, n_regions,
                         avg_ent, region_dicts, largest_region, avg_region_size) -> dict:
    findings = {
        "image_details": {
            "filename":      filename,
            "sha256":        sha256,
            "size_bytes":    size_bytes,
            "size_human":    size_human,
            "total_blocks":  total_blocks,
            "block_size":    "512 bytes",
        },
        "statistical_summary": {
            "suspicious_blocks":    susp,
            "suspicious_coverage":  f"{coverage_pct:.2f}%",
            "distinct_regions":     n_regions,
            "avg_suspicious_entropy": round(avg_ent, 3),
            "entropy_interpretation": _entropy_interpretation(avg_ent),
        },
        "region_summary": {
            "total_regions":      n_regions,
            "avg_region_size":    _fmt_bytes(int(avg_region_size)),
            "largest_region":     {
                "size":       _fmt_bytes(largest_region["size"]) if largest_region else "N/A",
                "type":       largest_region.get("type", "N/A") if largest_region else "N/A",
                "start":      f"0x{largest_region['start']:08X}" if largest_region else "N/A",
                "confidence": f"{largest_region.get('confidence', 0):.1%}" if largest_region else "N/A",
            },
            "regions_detail": [
                {
                    "id":         r.get("id"),
                    "type":       r.get("type"),
                    "start_hex":  f"0x{r['start']:08X}" if 'start' in r else "N/A",
                    "end_hex":    f"0x{r['end']:08X}" if 'end' in r else "N/A",
                    "size_human": _fmt_bytes(r.get("size", 0)),
                    "entropy":    r.get("entropy", 0),
                    "confidence": f"{r.get('confidence', 0):.1%}",
                    "blocks":     r.get("block_count", 0),
                }
                for r in region_dicts[:20]  # first 20 regions
            ],
        },
    }
    return findings


def _entropy_interpretation(avg_entropy: float) -> str:
    if avg_entropy >= 7.5:
        return ("Near-maximum entropy (≥7.5 bits/byte). Consistent with cryptographically "
                "random overwrite or encrypted data. Strong wipe indicator when combined "
                "with flat byte distribution.")
    elif avg_entropy >= 6.0:
        return ("High entropy (6.0-7.5 bits/byte). Consistent with compressed data, "
                "multi-pass wipe patterns, or mixed legitimate/wiped content.")
    elif avg_entropy <= 0.5:
        return ("Near-zero entropy (≤0.5 bits/byte). Consistent with deliberate fill-wipe "
                "(0x00 or 0xFF overwrite). Strong single-pass wipe indicator.")
    else:
        return f"Moderate entropy ({avg_entropy:.2f} bits/byte). Ambiguous — requires region context."


def _pattern_analysis(wipe_types, region_dicts, has_random, has_multi,
                       has_zero, has_ff) -> dict:
    analysis = {"types_detected": [], "tool_attribution": [], "interpretation": ""}

    active_types = {k: v for k, v in wipe_types.items() if v > 0}

    for wtype, count in sorted(active_types.items(), key=lambda x: -x[1]):
        sig = _TOOL_SIGNATURES.get(wtype, {})
        analysis["types_detected"].append({
            "type":        wtype,
            "block_count": count,
            "tools":       sig.get("tools", ["Unknown"]),
            "standard":    sig.get("standard", ""),
            "context":     sig.get("context", ""),
        })

    # Tool attribution (which tools most likely used)
    likely_tools = set()
    if has_multi:
        likely_tools.update(["DBAN (Gutmann/DoD mode)", "shred -n 3+", "Blancco", "Eraser"])
    elif has_random and has_zero:
        likely_tools.update(["shred (multi-pass)", "DoD 5220.22-M wiper", "sdelete -p"])
    elif has_random:
        likely_tools.update(["shred", "dd if=/dev/urandom", "Eraser (random pass)", "srm"])
    elif has_zero:
        likely_tools.update(["dd if=/dev/zero", "sdelete -z", "cipher /w:", "TRIM"])
    elif has_ff:
        likely_tools.update(["hdparm --security-erase", "Flash memory erase", "firmware wipe"])

    analysis["tool_attribution"] = list(likely_tools)

    # Interpretation
    if has_multi:
        analysis["interpretation"] = (
            "The combination of alternating zero, 0xFF, and random wipe bands in consecutive "
            "disk regions is a forensic signature of multi-pass overwrite tools. This pattern "
            "cannot occur naturally through filesystem operations and constitutes strong "
            "evidence of deliberate, methodical anti-forensic activity."
        )
    elif has_random and (has_zero or has_ff):
        analysis["interpretation"] = (
            "Multiple wipe modalities detected. The co-occurrence of random overwrite and "
            "fill-based wipes in adjacent regions suggests multiple erasure passes or "
            "different tools used on the same drive. This is uncommon in routine disk use."
        )
    elif has_random:
        analysis["interpretation"] = (
            "Cryptographically random overwrite detected. The near-flat byte distribution "
            "in affected blocks distinguishes wipe tool output from legitimate high-entropy "
            "data such as compressed files or encrypted volumes, which retain subtle "
            "structural bias in their byte distributions."
        )
    elif has_zero or has_ff:
        analysis["interpretation"] = (
            "Single-byte fill overwrite (zero and/or 0xFF) detected. While this pattern "
            "can appear naturally in unwritten sectors, the detected regions exceed the "
            "minimum threshold for deliberate wipe activity and are distributed in a "
            "pattern inconsistent with normal filesystem allocation."
        )
    else:
        analysis["interpretation"] = (
            "No confirmed strong wipe patterns detected. Observed partial patterns may "
            "reflect filesystem metadata, sparse file tails, or normal sector management."
        )

    return analysis


def _reliability_assessment(score, verdict, density, n_regions,
                              avg_ent, wipe_types, ml_summary) -> dict:
    caveats = []
    confidence_factors = []

    # Strong confidence factors
    if density > 0.30:
        confidence_factors.append("High wipe density (>30% of disk) — strong coverage signal")
    if wipe_types.get("RANDOM_WIPE", 0) > 0:
        confidence_factors.append("Random wipe detected — CSPRNG output distinguishable from compressed data")
    if wipe_types.get("MULTI_PASS", 0) > 0:
        confidence_factors.append("Multi-pass alternating bands confirmed — cannot occur naturally")
    if n_regions >= 3:
        confidence_factors.append(f"Multiple distinct regions ({n_regions}) indicate targeted wiping")

    # Caveats / uncertainty
    if density < 0.05:
        caveats.append("Low wipe density (<5%) — findings should be corroborated with other evidence")
    if avg_ent >= 7.0 and wipe_types.get("RANDOM_WIPE", 0) > 0:
        caveats.append(
            "High-entropy blocks overlap with legitimate compressed/encrypted data signatures. "
            "ML classifier was applied to reduce false positives, but some uncertainty remains "
            "without access to filesystem metadata."
        )
    if verdict == "MEDIUM" and n_regions < 3:
        caveats.append("Limited number of regions reduces statistical confidence in verdict")
    if wipe_types.get("LIKELY_ZERO_WIPE", 0) > wipe_types.get("ZERO_WIPE", 0):
        caveats.append(
            "Partial wipe evidence (LIKELY_ZERO_WIPE) exceeds confirmed wipe evidence. "
            "Partial patterns can appear in legitimate filesystem structures. "
            "Confirmed regions are present, but overall evidence strength is moderate."
        )

    # Reliability score
    if len(confidence_factors) >= 3 and len(caveats) <= 1:
        reliability_level = "HIGH"
        reliability_desc = "Analysis confidence is high. Multiple independent lines of evidence converge."
    elif len(confidence_factors) >= 2:
        reliability_level = "MEDIUM"
        reliability_desc = "Analysis confidence is moderate. Core findings are well-supported but some ambiguity exists."
    else:
        reliability_level = "LOW"
        reliability_desc = "Analysis confidence is limited. Results should be treated as preliminary."

    return {
        "reliability_level": reliability_level,
        "description":       reliability_desc,
        "confidence_factors": confidence_factors,
        "caveats":           caveats,
        "examiner_guidance": (
            "A qualified digital forensics examiner should review the raw entropy "
            "profiles, hex data from flagged regions, and filesystem context before "
            "drawing final conclusions. This automated analysis does not substitute "
            "for expert human review."
        ),
    }


def _ml_section(ml_summary: Optional[dict]) -> dict:
    if not ml_summary:
        return {
            "available": False,
            "note": "ML classification not performed or results unavailable.",
        }

    overrides = ml_summary.get("overrides", 0)
    fp_reductions = ml_summary.get("false_positive_reductions", 0)
    blocks_analyzed = ml_summary.get("blocks_analyzed", 0)
    model_version = ml_summary.get("model_version", "unknown")

    return {
        "available":             True,
        "model_version":         model_version,
        "blocks_analyzed":       blocks_analyzed,
        "total_overrides":       overrides,
        "false_positive_reductions": fp_reductions,
        "description": (
            f"ML ensemble classifier (Random Forest + Isolation Forest, model {model_version}) "
            f"analyzed {blocks_analyzed:,} blocks. "
            f"The model identified {overrides} cases where rule-based classification "
            f"was overridden, including {fp_reductions} likely false positives "
            f"(legitimate high-entropy data misclassified as wipe by rule engine). "
            "This reduces the false-positive rate for compressed/encrypted legitimate data."
        ) if blocks_analyzed > 0 else "ML classification was not applied.",
        "methodology": (
            "24-dimensional feature vectors were extracted from each block including: "
            "Shannon entropy, byte distribution uniformity, bigram autocorrelation, "
            "spectral flatness, serial correlation, format magic detection, and "
            "8 byte-range bucket profiles. A Random Forest (100 trees) trained on "
            "synthetic labeled data distinguishes CSPRNG wipe output from legitimate "
            "compressed/encrypted data. An Isolation Forest detects novel wipe patterns "
            "not covered by rule-based classification."
        ),
    }


def _conclusions(verdict, score, filename, has_random, has_multi,
                  n_regions, coverage_pct, density) -> dict:

    if verdict == "HIGH":
        opinion = (
            f"It is the opinion of this analysis system that the disk image '{filename}' "
            f"contains strong forensic evidence of deliberate anti-forensic wiping activity. "
            f"The distribution, density ({coverage_pct:.1f}% coverage), and character of "
            f"wipe artefacts detected are inconsistent with normal filesystem operation "
            f"and are consistent with the intentional use of data destruction software. "
        )
        if has_multi:
            opinion += (
                "The presence of alternating multi-pass wipe patterns is particularly "
                "significant, as this pattern has no plausible innocent explanation "
                "and is a hallmark of purpose-built secure erasure tools."
            )
        elif has_random:
            opinion += (
                "The cryptographically random overwrite patterns detected are consistent "
                "with tools specifically designed to defeat forensic recovery."
            )

    elif verdict == "MEDIUM":
        opinion = (
            f"The forensic evidence from '{filename}' is moderately indicative of "
            f"deliberate data elimination. While wipe artefacts are present across "
            f"{n_regions} region{'s' if n_regions != 1 else ''} with {coverage_pct:.1f}% "
            f"disk coverage, the evidence alone is not sufficient for a definitive "
            f"conclusion without additional context. This analysis should be considered "
            f"alongside other investigative findings."
        )

    elif verdict == "LOW":
        opinion = (
            f"The forensic evidence from '{filename}' shows limited wipe indicators "
            f"that are insufficient to support a conclusion of deliberate anti-forensic "
            f"activity. The detected anomalies may reflect normal disk operations, "
            f"filesystem management, or legacy data patterns. Further investigation "
            f"is recommended before drawing conclusions."
        )

    else:  # NEGLIGIBLE
        opinion = (
            f"No significant forensic evidence of deliberate data wiping was detected "
            f"in '{filename}'. The disk image appears consistent with normal use. "
            f"The absence of wipe evidence does not preclude prior wiping — "
            f"if a full-disk wipe was performed, the entire image may appear uniform "
            f"(not detectable by this method without original baseline)."
        )

    return {
        "forensic_opinion": opinion,
        "intent_score":     score,
        "verdict":          verdict,
        "confidence_note": (
            "This conclusion is based on automated analysis only. "
            "A qualified forensic examiner must review and validate these findings "
            "before any legal or investigative action is taken."
        ),
    }


def _recommended_actions(verdict, has_random, has_multi, n_regions,
                          score=0, has_zero=False, has_ff=False,
                          coverage_pct=0.0) -> list:
    """
    Generate recommended actions that are strictly consistent with the
    assigned verdict and intent score — no HIGH-priority actions on a
    LOW or NEGLIGIBLE verdict, no recommendations that contradict the findings.
    """
    actions = []

    if verdict == "HIGH":
        actions.append({
            "priority": "IMMEDIATE",
            "action":   "Preserve and Isolate Evidence",
            "detail":   f"Intent score {score}/100 indicates strong deliberate sanitisation. "
                        "Immediately create a verified forensic copy (write-blocked) and store "
                        "the original in a secure evidence locker. Do not power-cycle the device.",
        })
        actions.append({
            "priority": "HIGH",
            "action":   "Assign Qualified Forensic Examiner",
            "detail":   f"{n_regions} wipe region{'s' if n_regions != 1 else ''} require "
                        "manual verification in a hex editor. Automated classification should "
                        "be treated as preliminary — a qualified digital forensics examiner "
                        "must review and sign off before any legal submission.",
        })
        actions.append({
            "priority": "HIGH",
            "action":   "Filesystem Metadata Carving",
            "detail":   "Carve MFT entries, FAT tables, $LogFile, and journal structures from "
                        "non-wiped regions to reconstruct which files occupied the sanitised areas "
                        "and when they were last accessed.",
        })
        if has_random or has_multi:
            actions.append({
                "priority": "HIGH",
                "action":   "Wipe Tool Identification",
                "detail":   "Examine Windows registry (MUICache, UserAssist, AppCompatCache, "
                            "prefetch files) or Linux ~/.bash_history and /var/log/syslog for "
                            "evidence of DBAN, sdelete, Eraser, shred, or BCWipe execution. "
                            "Cross-reference with the detected wipe pattern signatures.",
            })
        if coverage_pct > 50:
            actions.append({
                "priority": "HIGH",
                "action":   "Full-Disk Sanitisation Confirmation",
                "detail":   f"Wipe regions cover {coverage_pct:.1f}% of the imaged disk — "
                            "consistent with full-disk wiping. Investigate whether the device "
                            "was factory-reset, enrolled in a remote wipe policy, or subject "
                            "to intentional evidence destruction.",
            })
        actions.append({
            "priority": "MEDIUM",
            "action":   "Timeline Correlation",
            "detail":   "Cross-reference wipe event timestamps (recoverable from partial "
                        "filesystem structures and journal fragments) against the investigation "
                        "timeline — login records, VPN logs, access control entries.",
        })
        actions.append({
            "priority": "MEDIUM",
            "action":   "Network and Cloud Artefact Review",
            "detail":   "Check cloud sync logs (OneDrive, Dropbox, Google Drive) and email "
                        "servers for copies of files that may have been stored in wiped regions "
                        "prior to deletion.",
        })

    elif verdict == "MEDIUM":
        actions.append({
            "priority": "HIGH",
            "action":   "Manual Region Verification",
            "detail":   f"Intent score {score}/100 — {n_regions} suspicious region{'s' if n_regions != 1 else ''} "
                        "detected. Manually inspect each flagged region in a hex editor to confirm "
                        "the automated classification before treating findings as conclusive.",
        })
        actions.append({
            "priority": "HIGH",
            "action":   "Filesystem Metadata Correlation",
            "detail":   "Carve filesystem metadata from non-wiped regions adjacent to the "
                        "flagged areas to determine whether wiped blocks previously contained "
                        "files, and if so, what type and when they were modified.",
        })
        if has_random or has_multi:
            actions.append({
                "priority": "HIGH",
                "action":   "Wipe Tool Artefact Search",
                "detail":   "Search the registry and shell history for known wipe tool signatures. "
                            "The detected random/multi-pass patterns are inconsistent with normal "
                            "filesystem operations and warrant tool attribution.",
            })
        actions.append({
            "priority": "MEDIUM",
            "action":   "Selective vs Full-Disk Assessment",
            "detail":   f"Coverage of {coverage_pct:.1f}% suggests targeted rather than full-disk "
                        "wiping. Identify whether the wiped regions correspond to specific "
                        "partitions, user directories, or file type clusters.",
        })
        actions.append({
            "priority": "LOW",
            "action":   "Expanded Image Acquisition",
            "detail":   "Consider acquiring unallocated space and slack space from the same "
                        "device using a separate forensic tool to recover any fragments that "
                        "this scan may not have captured.",
        })

    elif verdict == "LOW":
        actions.append({
            "priority": "MEDIUM",
            "action":   "Supplementary Manual Review",
            "detail":   f"Intent score {score}/100 — {n_regions} region{'s' if n_regions != 1 else ''} "
                        "flagged but below the confidence threshold for confirmed deliberate wiping. "
                        "Manually inspect each region to distinguish potential wipe artefacts "
                        "from compressed data, encrypted volumes, or filesystem padding.",
        })
        actions.append({
            "priority": "MEDIUM",
            "action":   "Alternative Explanation Assessment",
            "detail":   "The detected patterns are statistically consistent with legitimate "
                        "high-entropy data (encrypted containers, compressed archives, VM disk "
                        "images). Confirm whether the device hosted encryption software, VMs, "
                        "or backup tools before escalating.",
        })
        actions.append({
            "priority": "LOW",
            "action":   "Contextual Investigation",
            "detail":   "Low-confidence findings should be interpreted in context of the wider "
                        "investigation. Corroborate with user activity logs, email, or witness "
                        "evidence before drawing conclusions about deliberate sanitisation.",
        })

    else:  # NEGLIGIBLE
        actions.append({
            "priority": "LOW",
            "action":   "No Immediate Forensic Action Required",
            "detail":   f"Intent score {score}/100 — no significant wipe artefacts detected. "
                        "Disk content is consistent with normal filesystem activity. No further "
                        "wipe-specific analysis is recommended at this time.",
        })
        actions.append({
            "priority": "LOW",
            "action":   "Retain Image for Reference",
            "detail":   "Archive the verified disk image and this report for the case file. "
                        "If new evidence emerges suggesting prior sanitisation, re-run the "
                        "analysis with updated classifier thresholds.",
        })

    # Always append — applies to all verdicts
    actions.append({
        "priority": "LOW",
        "action":   "Evidence Hash Verification",
        "detail":   "Re-hash the stored disk image and compare against the acquisition SHA-256 "
                    "recorded in the chain of custody to confirm integrity has been maintained "
                    "throughout the analysis workflow.",
    })

    return actions


# ─────────────────────────────────────────────────────────────────────────────
# UTILITY
# ─────────────────────────────────────────────────────────────────────────────

def _fmt_bytes(b: int) -> str:
    if b == 0:
        return "0 B"
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if b < 1024:
            return f"{b:.2f} {unit}"
        b //= 1024
    return f"{b:.2f} PB"
